services:
  postgres:
    image: postgres:16
    container_name: s2o-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: s2o_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - s2o-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: s2o-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - s2o-network

  api:
    image: s2o-api:test
    build: .
    container_name: s2o-api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      # QUAN TRỌNG: QR phải trỏ gateway
      BASE_URL: http://localhost:8001/api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - s2o-network

  gateway:
    image: nginx:alpine
    container_name: s2o-gateway
    ports:
      - "8001:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - s2o-network


networks:
  s2o-network:
    driver: bridge

volumes:
  postgres_data:
